# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 517696848deba525a0f119266d6be4446c0a32d6abd551c1a493225433a552343593216f0789ec8ba168886b31d78dd3cbd6aad71f1751c7ee9e156dcbe37a34

test:
  secret_key_base: 3d8c698c79c7f7ea396cf9202931c725bbde929d3d0af4508de8159ee7c97364ed53f69fe65b2c0764ea8a0ccbea5c7640d9232f36f31aef2feb7c0294ff1d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
